#version 460 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Particle{
    vec4 position;
    vec4 velocity;
}

layout(std430, binding = 0) buffer ParticleBuffer{
    Particle particles[];
};

uniform float u_DeltaTime;
uniform vec3 u_EmitterPosition;
uniform uint u_EmitMaxCount;

float hash11(uint x) {
    x = ((x >> 16) ^ x) * 0x45d9f3bu;
    x = ((x >> 16) ^ x) * 0x45d9f3bu;
    x = (x >> 16) ^ x;
    return float(x) / 4294967295.0;
}

void main(){
    uint id = gl_GlobalInvocationID.x;

    if(id >= particles.length()){
        return;
    }
}