name: andromeda_launcher
description: Andromeda game engine launcher
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  window_manager: ^0.5.1
  url_launcher: ^6.3.2
  http: ^1.6.0
  file_picker: ^8.1.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
